#include "std_lib_facilities.h"

int main()
{
	// exercise 2 - miles to km converter
	float miles;
	float km;
	float conversion = 1.609;

	cout << "enter miles ";
	cin >> miles; 
	km = miles * conversion;
	cout << "That in kilometers is " << km << "km" << "\n";

	// exercise 3 - illegal names
	//int double = 0;
	//int _number = 5; // compiler doesn't react, bu dont use nonetheless, clashed with names generated by the compiler
	//int 5%of7 = 1;

	// exercise 4 - calculator, with some extra features
	int num1;
	int num2;
	bool num1big;

	cout << "enter 2 numbers pls " << "\n ";
	cin >> num1;
	cin >> num2;

	// bigger or smaller

	if (num1 > num2)
	{
		cout << num1 << " is bigger than " << num2 << "\n ";
		num1big = true;
	}
	else if (num2 > num1)
	{
		cout << num2 << " is bigger than " << num1 << "\n ";
		num1big = false;
	}
	else
	{
		cout << "you entered the same number" << "\n ";
	}

	// sums
	int sum = num1 + num2;
	int product = num1 * num2;
	int dif;
	int ratio;

	if (num1big)
	{
		dif = num1 - num2;
	}
	else if (!num1big)
	{
		dif = num2 - num1;
	}
	else
	{
		dif = 0;
	}

	if (num1big)
	{
		ratio = num1 / num2;
	}
	else if (!num1big)
	{
		ratio = num2 / num1;
	}
	else
	{
		ratio = 1;
	}

	cout << "sum is " << sum << "\n" << "product is " << product << "\n" << "difference is " << dif << "\n" << "ratio is " << ratio << "\n";

	
	


}

