#include "std_lib_facilities.h"

int main()
{
	// exercise 2 - miles to km converter
	float miles;
	float km;
	float conversion = 1.609;

	cout << "enter miles ";
	cin >> miles; 
	km = miles * conversion;
	cout << "That in kilometers is " << km << "km";

	// exercise 3 - illegal names
	//int double = 0;
	//int _number = 5; // compiler doesn't react, bu dont use nonetheless, clashed with names generated by the compiler
	//int 5%of7 = 1;


}

